### ISSUE TITLE
Survey display

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#106]
![wttq](https://f.cloud.github.com/assets/944656/1418463/2ea09800-3fb5-11e3-924a-bb2b69e2dc3a.jpg)

I'm on a PC and Firefox 24.0. The display of the survey is a bit difficult for me - the radio button for 'disagree' is on the line before the word 'disagree', for example, and the questions are too tightly bunched together. It's hard to tell which answers belong to which question.

**Comment by zarino** [comment]
This page was introduced as part of the [UCL A/B Testing pull request](https://github.com/mysociety/writetothem/pull/81) and has since been removed. The new page just has two simple buttons:

![screen shot 2015-06-03 at 11 02 12](https://cloud.githubusercontent.com/assets/739624/7957542/0946e162-09e0-11e5-914d-e0a384e14d1e.png)

So I guess we can mark this as fixed!

**Comment by dracos** [comment]
1 in 30 people (see web/firsttime.php) are still getting templates/website/survey-questions.html – if this survey data isn't being used by anyone, then this survey should be switched off!

**Comment by zarino** [comment]
@jacksonj04 and @Rebeccarumbul are best placed to say whether this survey page is still required. (You can [see the HTML content here](https://github.com/mysociety/writetothem/blob/master/templates/website/survey-questions.html)) – if the data gathered by that form is still useful, I can make sure the form is styled up properly, otherwise we should just delete it.

**Comment by dracos** [comment]
Removed in 3d2da946367f0f5d49cd3cbc07b516c3b607a530
