### ISSUE TITLE
Totally redesign responsiveness stats pages

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/writetothem#163]
### Essentials

* [ ] Make the whole thing less sucky.
* [ ] If we link to the stats page, do people still see the tab with the summary on it?
* [ ] Is the data and methodology clear enough?
* [ ] Can we make the tweet button more prominent/enticing and add a FB button?

### Optional Goodies

* [ ] Include "This MP was new in this Parliament" indicator
* [ ] Include movement indicator

**Comment by MyfanwyNixon** [comment]
Bumping this up so that the stats pages get a design overhaul before 2016.

This year we made a few tweaks before going live, but in a hurry and without an eye to things like:
- If we link to the stats page, do people still see the tab with the summary on it?
- Is the data and methodology clear enough?
- Can we make the tweet button more prominent/enticing and add a FB button?

**Comment by jacksonj04** [comment]
:+1: – the stats pages could really do with a bit more time spent on them in general (eg see also #241)

**Comment by MyfanwyNixon** [comment]
Adding the word 'responsiveness' to this thread, as it's what I most often search for in relation to these pages.

**Comment by zarino** [comment]
Pull request here, with a first version of this, and a list of further suggested improvements:

https://github.com/mysociety/writetothem/issues/317
