### ISSUE TITLE
Manage user expectations post-election

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#245]
If it is likely to take some time before local councillor and MP details are available on WTT, can we add a comprehensive message to the reps page, in an effort to cut down on the amount of user support mail saying 'The election was x days ago, get with the programme?'.

It should be enough to say something like: "Apologies: we have not yet imported post-election data. Typically, there is a time lag as we rely on data from external sources. If you need to contact your MP/councillors urgently, you should be able to find their contact details on the Parliament website [link] or your council website. If you do not know who your MP is, please input your postcode on TheyWorkForYou.com to find out".

**Comment by dracos** [comment]
The current messages are:
"Due to the recent election, we don’t yet have details for this representative.  We’ll be adding them as soon as we can."
or if there are boundary changes:
"There have been boundary changes at the last election that means we can’t yet say who your representative is. We hope to get our boundary database updated as soon as we can."

**Comment by MyfanwyNixon** [comment]
We've had a good number of enquiries via email and Twitter which ask exactly when we are likely to have the data. Could we add at least a loose estimate on timings, please?

**Comment by dracos** [comment]
MPs are live again now. For others, I've updated the text a bit as discussed.
