### ISSUE TITLE
User suggestion: Leeds Town Hall not suitable for hero image

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#257]
>   Wouldn't the Houses of Parliament be a more appropriate building to show on your masthead than Leeds Town Hall?

I am aware we chose this image because we wanted to show there is more to WTT than just writing to MPs. I suppose we could have a random assortment of different buildings, on rotation.

**Comment by jacksonj04** [comment]
Leeds Town Hall was chosen because it was a building which was obviously "civic" in nature, without being as famous a view as the Houses of Parliament (unless you happen to live in Leeds). We could be remarkably Web 3.0 and have the hero image fading between a series of buildings, which would make @zarino happy.

**Comment by MyfanwyNixon** [comment]
On reflection: we probably also ought to set some kind of a baseline on how much we do based on a single user's comment :)

I tend to record them because you never know when a single comment could be the beginning of a flood, but, y'know, this has been the only comment about this so far.

**Comment by zarino** [comment]
Yeah, I'd leave it as-is. Unless we have some evidence that it's actively putting off users.
