### ISSUE TITLE
extref urls working oddly?

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#275]
A user writes:
>  The URL link to my MP Kate Green takes me to Jeremy Corbyn.
> on page URL https://www.writetothem.com/who?pc=M32+0RQ&fyr_extref=http%3A%2F%2Fwww.theyworkforyou.com%2Fmp%2F10133%2Fjeremy_corbyn%2Fislington_north
> following my PostCode search.

I just clicked it myself and it took me to Kate Green ok, but given that we also had another query about a URL with extref in it (see below), I wondered whether there might be something that needs looking at.

>  I regularly use your site to establish the Ward for a
     given Postcode, however today the site is being blocked by our
     web filters, as your search function is now adding
     "&fyr_extref=http%3A%2F%2Fm.facebook.com" to the result page
     url upon searching

Follow-up:

> I was navigating to the page via direct url or via google, as I have always done . The issu hadn’t arisen before but I have tried again this morning and the problem appears to have resolved itself, somehow

**Comment by dracos** [comment]
The extref is not used for anything bar recording where someone has come from. That link will never take you to Jeremy Corbyn, that URL just means they came to WriteToThem from Jeremy Corbyn's page on TheyWorkForYou. If something is blocking URLs because they have 'facebook.com' somewhere within them (rather than actually being on that domain), that is a really crap web filter, I'm not sure there is anything we can do beyond asking them to complain about their crap web filter.
