### ISSUE TITLE
MessageLabs (used by parliament.uk) mail server (195.245.230.39) listed in Spamhaus

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#285]
Messages for Jeff Smith MP
eg message ID: 190e99729616bc79aba9

A bounce message states:
> Diagnostic-Code: smtp; 550 5.7.1 Service unavailable; Client host [195.245.230.39] blocked using Spamhaus; To request removal from this list see http://www.spamhaus.org/lookup.lasso

**Comment by MyfanwyNixon** [comment]
Also see ID e24da5be2a7faaff5d5d, Vicky Foxcroft and 	29b040112ad4762a2176 Chris Philp - I wonder if several MPs have just implemented this, as this morning's inbox has a number of messages proffering email addresses that turn out to be because messages bounced.

**Comment by MyfanwyNixon** [comment]
Also with same bounce messages:
Geraint Davies
Jim Cunningham (user provided an alternative email address, which I've put in)
Alan Whitehead (ditto)
Helen Hayes

**Comment by dracos** [comment]
That error says that Messagelabs (which is parliament.uk's presumably outsourced mail server) has been entered into spamhaus, the spam spotting service, and then so an internal server at messagelabs is blocking their own message. The issue is with parliament.uk/messagelabs, not us, the same will be happening to others emailing parliament addresses, and someone should let parliament know.

**Comment by dracos** [comment]
Looks like they're not listed any more, so presumably will sort itself out if messages get retried.

**Comment by MyfanwyNixon** [comment]
Thanks - have done so.

**Comment by MyfanwyNixon** [comment]
Continues; re-opening (and am emailing parliament)
