### ISSUE TITLE
Promote responsiveness league table on WTT homepage

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#308]
We'd like something more visible than the flash at the very top of the page - a "How well does your MP respond?" design element that's a bit more in your face.

**Comment by zarino** [comment]
Current thinking is that we replace the hero on the homepage, and then move the "Write to your politicians…" heading down into the white section.

That way we'll have lots of space for a big feature on the stats.

**Comment by zarino** [comment]
I figure we can afford to be bold with this, especially since it's only a limited-time promotion. How about something like this…

![screen shot 2016-05-13 at 11 16 19](https://cloud.githubusercontent.com/assets/739624/15245041/3347f678-18fc-11e6-932f-03403effd45e.png)

Thoughts @paullenz @wrightmartin @dracos?

**Comment by wrightmartin** [comment]
👍 

Do we have any copy for the same type of feature on external sites? It would be nice to be consistent with terms - are these ratings, statistics, reports etc

**Comment by MyfanwyNixon** [comment]
I think clarity is the most important thing here. Originally we were looking at 'Zeitgeist' but I think a portion of our users won't recognise that word or associate it with what we are promoting.

In fact I think 'Find out now' would do very well for the button placement as above.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/writetothem/pull/318
