### ISSUE TITLE
Confusing MEPs message

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#324]
On a page such as https://www.writetothem.com/who?pc=RG45+6US we display the message:

> Some MEPs for your region have informed us that they have divided it into areas, with one MEP dealing with constituent correspondence per area, so we only show that MEP above; you can contact the others here:
- A user has written to ask why clicking the 'write to all MEPs' has not included the constituency MEP/s - suspect this is similar to #104 - perhaps using the same code?
- We actually list 2 MEPs in that section
- They are below the note and not above it, and the others are to the left of that note and not below it as the wording would suggest

**Comment by dracos** [comment]
If you look at it at a smaller width, it makes more sense as above/below are correct then. Clicking 'write to all MEPs" *has* included the constituency MEPs, the ones listed separately are the *non* constituency MEPs. This is just a wording issue due to above/below not making sense in this layout, the list and links are doing the correct thing.
