### ISSUE TITLE
Typeface could be better for dyslexic users

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#335]
>My issue is that I have dyslexia - and there's plenty more like
     me out there.

>Serif fonts, such as Times New Roman, can cause us particular
     difficulties with reading. In contrast, sans serif fonts, such
     as Helvetica or Arial, are generally easier to read.

> The default font here seems to be something like Times New
     Roman.

> I wonder whether it would be possible to amend this, and use a
     sans serif font throughout your site?

FAO: @wrightmartin @zarino

**Comment by zarino** [comment]
I am sorry to be the person who breaks this news, but no, we're not changing to sans-serif.

I expect we are not the only serif-typeset website this user has come across.

Has the user considered [editing their browser’s user stylesheet](http://www.lostsaloon.com/technology/using-a-custom-stylesheet-in-a-web-browser/) to force websites like ours to use the typeface of their choice? There are also third-party plugins like [Stylebot for Chrome](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha) that give you point-and-click buttons and menus to alter all sorts of parameters about the webpages you visit, including the typeface.

**Comment by MyfanwyNixon** [comment]
Blimey you designers are so hardline :) 
Are there advantages to serif, apart from the look? Eg, is it easier for non-dyslexic people to read?

**Comment by wrightmartin** [comment]
@MyfanwyNixon 

http://alexpoole.info/blog/which-are-more-legible-serif-or-sans-serif-typefaces/ This is worth a read. TLDR: For general legibility nobody knows for sure, because the research conducted often conflicts with other research. So it's sensible to guestimate they are equally legible. 

As for dyslexia, it's not the style of the typeface (eg serif'd or not) but the construction of distinct letters (such as making 'b' and 'd' look as different as possible). 

---

I agree with Zarino - if our typefaces used on WriteToThem cause a problem for this particular visitor, their best bet would be to use a user stylesheet, as it would change our website and every other one they visit as a bonus

**Comment by MyfanwyNixon** [comment]
Good to know, thank you!
