### ISSUE TITLE
Investigate Admin timeout on search 

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/writetothem#361]
@MyfanwyNixon has been experiencing timeouts when trying to run search queries on the administration section of WTT.

@MyfanwyNixon could you give us some more information on what happens and if it's only with the Kevin Brennan MP question or with others

**Comment by MyfanwyNixon** [comment]
So this was triggered by trying to see all previous mails sent to Kevin Brennan, via the 'search for WriteToThem messages' link on his [match.cgi entry](https://www.writetothem.com/admin/index.php?page=reps&pc=&rep_id=46797), which leads to:

https://www.writetothem.com/admin/index.php?page=reps&page=fyrqueue&rep_id=46797

What happens is that I just get a blank screen.

My hunch is that this happens when there are too many records to be presented, in which case it would correlate with either long parliamentary careers or large mailbags. For example, an MP who was new in 2015 will load ok: https://www.writetothem.com/admin/index.php?page=reps&page=fyrqueue&rep_id=61871.

Another search that will make a request time out is in the message queue, searching for a name that's relatively common, for example, which would back up the theory that it's just when there are too many results.

**Comment by jacksonj04** [comment]
Pagination of results would be awesomesauce.

**Comment by dracos** [comment]
Done
